version: "3"

networks:
  1panel-network:
    external: true

services:
  lunatv:
    image: ghcr.io/moontechlab/lunatv:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - NEXT_PUBLIC_STORAGE_TYPE=${STORAGE_TYPE}
      - KVROCKS_URL=redis://lunatv-kvrocks:6666
    depends_on:
      - lunatv-kvrocks
    labels:
      createdBy: "Apps"

  lunatv-kvrocks:
    image: apache/kvrocks
    container_name: ${CONTAINER_NAME}-kvrocks
    restart: unless-stopped
    networks:
      - 1panel-network
    volumes:
      - ./data:/var/lib/kvrocks
    labels:
      createdBy: "Apps"
