version: "3"

networks:
  1panel-network:
    external: true

services:
  lunatv:
    image: ghcr.io/moontechlab/lunatv:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - NEXT_PUBLIC_STORAGE_TYPE=${STORAGE_TYPE} # 动态决定使用 kvrocks/redis/upstash
      - KVROCKS_URL=redis://lunatv-kvrocks:6666
      - REDIS_URL=redis://lunatv-redis:6379
      - UPSTASH_URL=${UPSTASH_URL}
      - UPSTASH_TOKEN=${UPSTASH_TOKEN}            
    depends_on:
      - lunatv-kvrocks
      - lunatv-redis
    labels:
      createdBy: "Apps"

  # 本地分布式 Kvrocks 数据库服务
  lunatv-kvrocks:
    image: apache/kvrocks:latest
    container_name: ${CONTAINER_NAME}-kvrocks
    restart: unless-stopped
    networks:
      - 1panel-network
    volumes:
      # 精准挂载到 db 目录，彻底杜绝之前找不到配置文件的报错
      - ./data/kvrocks:/var/lib/kvrocks/db 
    labels:
      createdBy: "Apps"

  # 本地高性能 Redis 数据库服务
  lunatv-redis:
    image: redis:alpine
    container_name: ${CONTAINER_NAME}-redis
    restart: unless-stopped
    networks:
      - 1panel-network
    volumes:
      - ./data/redis:/data
    labels:
      createdBy: "Apps"