networks:
  1panel-network:
    external: true

services:
  lx-music-sync:
    image: lyswhut/lx-music-sync-server:v2.1.2
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9527"
    environment:
      - PORT=9527
      - BIND_IP=0.0.0.0
      - SERVER_NAME=${SERVER_NAME}
      - MAX_SNAPSHOT_NUM=${MAX_SNAPSHOT_NUM:-1}
      - DATA_PATH=/app/data
      - LX_USER_admin=${LX_USER_ADMIN_PASSWORD}
      - LX_USER_dingdang=${LX_USER_DINGDANG_PASSWORD}
      - LX_USER_testuser=${LX_USER_TESTUSER_PASSWORD}
    volumes:
      - ./data:/app/data
    labels:
      createdBy: "Apps"
