version: '3'

networks:
    1panel-network:
        external: true
services:
  iptv-api:
    image: guovern/iptv-api:2.0.7
    container_name: ${CONTAINER_NAME}-service
    deploy:
        resources:
            limits:
                cpus: ${CPUS}
                memory: ${MEMORY_LIMIT}
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080" 
    volumes:
      - ./data/config:/iptv-api/config 
      - ./data/output:/iptv-api/output 
    environment:
      TZ: "Asia/Shanghai"
      PUBLIC_SCHEME: "http"
      PUBLIC_DOMAIN: "${PUBLIC_DOMAIN}" 
      PUBLIC_PORT: "${PUBLIC_PORT}"     
      NGINX_HTTP_PORT: "8080"
      CDN_URL: ""
      HTTP_PROXY: ""
    labels:
      createdBy: "Apps"