networks:
  1panel-network:
    external: true

services:
  cc-switch-web:
    image: ghcr.io/laliet/cc-switch-web:0.21.0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    volumes:
      - ./data:/home/ccswitch/.cc-switch
    labels:
      createdBy: "Apps"
